---
version: '3'

networks:
    kafka-net:
      driver: bridge

services:
    # selenium-tests:
    #     build:
    #       context: .
    #       dockerfile: docker/selenium-tests/Dockerfile
    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        networks:
        - kafka-net
        ports:
        - '2181:2181'
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

    kafka-server:
        image: 'bitnami/kafka:latest'
        networks:
        - kafka-net    
        ports:
        - '9092:9092'
        environment:
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
        - zookeeper-server

    # kafka-server2:
    #     image: 'bitnami/kafka:latest'
    #     networks:
    #     - kafka-net    
    #     ports:
    #     - '9093:9092'
    #     environment:
    #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
    #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
    #     - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on:
    #     - zookeeper-server

    timescaledb:
        build:
            context: .
            dockerfile: docker/timescaledb/Dockerfile
        environment: 
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432